# Artificial Neural Network

**Data Set:** Churn_Modelling.csv

BAsed on the different details of the user and their activity we as a bank need to predict if the person leaves the bank or not 

0 means doesnt leave

1 menas leaves the bank

### Importing the libraries

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [23]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [0]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [25]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [26]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [0]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [28]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [30]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [0]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))   #6 neurons


### Adding the second hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu')) # 6 neurons

### Adding the output layer

In [0]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))  #1 neuron because the output is binary 


## Part 3 - Training the ANN

### Compiling the ANN

In [0]:
ann.compile(optimizer='adam', loss='binary_crossentropy' ,metrics=['accuracy']) #adam performs stochastic gradient decend
#One Epoch is when an ENTIRE dataset is passed forward and backward through the neural network only ONCE. 
#batch size is the number of prediction to be made to compare with the real value


### Training the ANN on the Training set

In [38]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)


Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6279 - accuracy: 0.7029
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4992 - accuracy: 0.7950
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4587 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4375 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4271 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4213 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4168 - accuracy: 0.7960
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4129 - accuracy: 0.7960
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4089 - accuracy: 0.7960
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4047 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [39]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


##Predicting the result of a single observation

Using our ANN model to predict if the customer with the following details will leave the bank or not

Geography: France

Credit Score : 200

Gender : Male

Age: 40 years old

Tenure : 3 years

Balance : $ 60000

Number of Products : 2

 Credit Card; Yes

Active Memeber : Yes

Estimated Salary : $ 50000

So should we say goodbye to the customer ? 


In [40]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))> 0.5)

[[False]]


false means we wont tell goodbye

### Making the Confusion Matrix

In [43]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1513   82]
 [ 199  206]]


0.8595